### PR TITLE
Release

### PR DESCRIPTION
**Pull request by nigelmann**
This PR will be merged once everything is ready for production

### CODE REVIEW

**Comment by HugoMendes98** [comment]
@nigelmann Let's wait until https://github.com/PDG-2023/Project/pull/84 is merge.
It contains the categories view. The other views will be a lot like that one.

**Comment by nigelmann** [comment]
I suggest we merge on Sunday evening

**Comment by nigelmann** [comment]
For now the production is not booted, everything should normaly boot when me merge :crossed_fingers:

**Review by noahboegli — APPROVED** [review]
Let's get that bachelor

**Pull request merged**
