### PR TITLE
Can compare with null (Integer fields only)

### PR DESCRIPTION
**Pull request by HugoMendes98**
Needed, for example, to get all categories without parents

@noahboegli If there's something wrong, feel free to correct

### CODE REVIEW

**Comment by noahboegli** [comment]
It would require some testing but I believe the whole condition can be turned down to `filterValue.equals("null")` and used for every data type. 

I'll check that and make changes if required.

Also, I'd argue against allowing an empty value to be considered as null

**Comment by HugoMendes98** [comment]
@noahboegli 

> Also, I'd argue against allowing an empty value to be considered as null

True, that why it's only for Integer for now.
To check, but when I was debugging, it seems that a `null` value was casted to an empty string `""`.

> I believe the whole condition can be turned down to filterValue.equals("null")

Unless someone is looking for a "null" string.
But I totally agree for dates and numbers.

**Comment by noahboegli** [comment]
Is the only use case the parent categories ? because if that's the case I'd suggest we ditch that and create a special route for root categories ?

**Comment by HugoMendes98** [comment]
`Location` too.

I'd rather have one endpoint and applying conditions, than special endpoints that apply conditions.

**Review by noahboegli — APPROVED** [review]

**Pull request merged**
