### PR TITLE
Real authentification

### PR DESCRIPTION
**Pull request by HugoMendes98**
Can now log-in and register with a real user.

The token is stored, so it is use when refreshing the page.

Related:
- https://github.com/PDG-2023/Project/issues/24.
- https://github.com/PDG-2023/Project/issues/34

### CODE REVIEW

**Review by nigelmann — CHANGES_REQUESTED** [review]
First of all thanks for all the good work.

I have tested the register and then login process.

I am missing a logout button, I can only disconnect by pressing F12 and deleting things (not the best interface).

I am ok with only having the email entered on register but the username should then be the part before the @
email: hello@gmail.com
username: hello

Maybe the register form could have an optional username field and if not field it set the username to default (like said before) ? 

I can adapt the getToken method to accept email and username. then le login form can say "email or username" 

What do you think ?

**Comment by HugoMendes98** [comment]
@nigelmann

I will add a logout button (was thinking doing it later).

For the register, I'd rather add a `username` field instead of "hacking" with the email.
For the login, let's do that. I send you something and you manage to determine if it is an email or username.
You (and I in the front) should probably forbid the `@` in the username then.

**Comment by nigelmann** [comment]
Agreed !

For the username I was thinking of doing a simple sequential search if usernam not found then check the email so in my opinion no need to restrict the @ in the username. But that is just my own opinion.

**Comment by HugoMendes98** [comment]
@nigelmann Username input added and a logout button from the profile page has been added.
Waiting for the login-with-an-email-or-username implementation from the backend.

**Pull request merged**
