### PR TITLE
Search filter

### PR DESCRIPTION
**Pull request by noahboegli**
This is a re-edition of #41  because I fucked up the history

@HugoMendes98's comment on this initial PR
----
> 
> > @HugoMendes98 I hope I managed to hold to your query filter standards, or at least come close to them.
>
>@noahboegli Close enough :).
>
>Some feedback:
>- Do the comparison operators support dates? Needed if we want to show only some items after a point in time.
>  - And what format do they expect? The standard ISO (`2000-01-01T12:00:00.000Z`)?
>- Given the current developed features, a `OR` filter does not seem needed at the moment.
>- What happens with a `limit=0`? Does it fail or return nothing (~count only)?
>- A sorting option is necessary; the application is first and foremost a list of items. If they can't be ordered, users have less reason to use it.
>  - An `order` object property would be ideal (ex: `order[0][id]=asc&order[1][name]=desc`), however, given the time limit, a simplier solution can be implemented (ex: `order=id,-name`, the `-` meaning _desc_).  
>  - I let you decide what's the easier.

### CODE REVIEW

**Comment by noahboegli** [comment]
@HugoMendes98  
Answers: 
- I believe they support dates, although we should look into that because Java is peculiar with dates :)
- Limit/offset are required to be together (do we need to change that?), if you put limit = 0 it will return no results. It's debatable so you tell me what behavior you'd like 
- Noted for the order, I'll see what I can implement

**Comment by HugoMendes98** [comment]
@noahboegli 

> I believe they support dates [...]

Ok, could you confirm that (by a simple request).
I'll take your word for it.

---

> Limit/offset are required to be together  

I'm fine with that.


> limit = 0 it will return no results  

Perfect.

---

Waiting for the last part.

**Comment by noahboegli** [comment]
Okay so time filtering was not supported. It is now @HugoMendes98 
`/api/inventories?where[createdAt][$gte]=2023-05-28T00:00:00&where[name][$neq]=Paul` for example. It's the `ISO_LOCAL_DATE_TIME` standard.

**Comment by noahboegli** [comment]
@HugoMendes98 
Do you need the ordering to be `n` depth or only on the current entity ?

**Comment by noahboegli** [comment]
Alright I have a first version

- Only on entity depth (i.e. no nested ordering)
- You can't specify indexes, since all filters are managed independently.
   -  Applied in order of appearance in URL

## Example

`/inventories?order[createdAt]=asc&order[name]=desc`  returns

```json
[
  {
    "id": 3,
    "updated": "27-05-2023 22:53:25",
    "created": "27-05-2023 22:53:25",
    "name": "test inventory"
  },
  {
    "id": 4,
    "updated": "27-05-2023 22:53:25",
    "created": "27-05-2023 22:53:25",
    "name": "AAAAAA"
  },
  {
    "id": 1,
    "updated": "28-05-2023 22:53:25",
    "created": "28-05-2023 22:53:25",
    "name": "test inventory"
  }
]
```

Does that work for you ?

**Comment by noahboegli** [comment]
Nota: 

If an unknown filter or an unknown option (ordering, comparison)  you receive a 400 describing the filter in question

**Comment by noahboegli** [comment]
Yep, the ordering is applied in the order that the fields were given.

I.e. `/inventories?order[createdAt]=asc&order[name]=desc` will order by creation date, then by name

Whereas `/inventories?order[name]=desc&order[createdAt]=asc` will order by name then by creation date

They don't need to be put all at the same place, only their appearance matter, ie
`/inventories?order[name]=desc&where[name][$eq]=Paul&order[createdAt]=asc` 

would yield the same result as

`/inventories?order[name]=desc&order[createdAt]=asc&where[name][$eq]=Paul`

**Review by HugoMendes98 — APPROVED** [review]

**Pull request merged**
